import React from "react";
import { render, screen } from "@testing-library/react";
import App from "../pages";
import getMetaContent from "../lib/getMetaContent";
const userStory = `
Given no inital state,
When user navigates to the web page,
Then user sees the static information
`;
describe(userStory, () => {
  beforeEach(() => {
    render(<App />);
  });
  it("shows the phrase Next.js!", () => {
    const linkElement = screen.getByText(/Next.js!/i);
    expect(linkElement).toBeInTheDocument();
  });
  it("shows the correct headers", () => {
    const titleCollection = document.getElementsByTagName("title");
    expect(titleCollection[0].text).toEqual("Create Next App");
    const metaCollection = document.getElementsByTagName("meta");
    const titleMeta = getMetaContent(0, (metaCollection as unknown) as HTMLMetaElement[], "title");
    expect(titleMeta)
      .toEqual("");
    const descriptionMeta = getMetaContent(0, (metaCollection as unknown) as HTMLMetaElement[], "description");
    expect(descriptionMeta)
      .toEqual("Generated by create next app");
  });
});
