export const APP_LOGIN_VIEW = "APP_LOGIN_VIEW";
export const APP_MAGIC_LINK_VIEW = "APP_MAGIC_LINK_VIEW";
export const APP_INVALID_EMAIL_VIEW = "APP_INVALID_EMAIL_VIEW";
export const APP_PROFILE_VIEW = "APP_PROFILE_VIEW";
export const APP_MANAGE_USERS_VIEW = "APP_MANAGE_USERS_VIEW";
export type APP_VIEW_TYPE =
  typeof APP_LOGIN_VIEW
  | typeof APP_MAGIC_LINK_VIEW
  | typeof APP_INVALID_EMAIL_VIEW
  | typeof APP_PROFILE_VIEW
  | typeof APP_MANAGE_USERS_VIEW
  | null
